type: web
name: custom-tts
runtime: python
rootDir: backend # 🔥 Ensure Render uses `backend/` as root
buildCommand: "pip install -r requirements.txt"
startCommand: "gunicorn wsgi:app --bind 0.0.0.0:$PORT"
plan: free
region: Ohio (US East)
deploy:
  autoDeploy: true
