name: Deploy Frontend to Render

on:
  push:
    branches:
      - main # Deploy whenever you push to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_FRONTEND_HOOK }}
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
